### ISSUE TITLE
Compilation problems under fedora 24

### ISSUE THREAD

**Issue by ycollet** [lenmus/lenmus#55]
I try to compile lenmus on fedora 24 (gcc version 6.1.1).
During compilation, I meet the following error:

```
[  3%] Building CXX object CMakeFiles/lenmus.dir/src/app/lenmus_canvas.cpp.o
[  3%] Building CXX object CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp: Dans la fonction membre ‘void lenmus::CommandEventHandler::process_command_event(lomse::SpEventCommand)’:
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:401:77: erreur : no matching function for call to ‘static_pointer_cast(lomse::SpEventCommand&)’
                     boost::static_pointer_cast<EventControlPointMoved>(event) );
                                                                             ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_ldp_elements.h:40,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_ldp_factory.h:38,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_injectors.h:33,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_interactor.h:34,
                 from /home/collette/repositories/lenmus/include/lenmus_tool_group.h:25,
                 from /home/collette/repositories/lenmus/include/lenmus_tool_box.h:26,
                 from /home/collette/repositories/lenmus/include/lenmus_command_event_handler.h:26,
                 from /home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:22:
/usr/include/boost/smart_ptr/shared_ptr.hpp:828:42: note : candidate: template<class T, class U> boost::shared_ptr<X> boost::static_pointer_cast(const boost::shared_ptr<U>&)
 template<class T, class U> shared_ptr<T> static_pointer_cast( shared_ptr<U> const & r ) BOOST_NOEXCEPT
                                          ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/smart_ptr/shared_ptr.hpp:828:42: note :   template argument deduction/substitution failed:
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:401:77: note :   ‘lomse::SpEventCommand {aka std::shared_ptr<lomse::EventCommand>}’ is not derived from ‘const boost::shared_ptr<U>’
                     boost::static_pointer_cast<EventControlPointMoved>(event) );
                                                                             ^
CMakeFiles/lenmus.dir/build.make:182 : la recette pour la cible « CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o » a échouée
make[2]: *** [CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o] Erreur 1
CMakeFiles/Makefile2:99 : la recette pour la cible « CMakeFiles/lenmus.dir/all » a échouée
```

**Comment by cecilios** [comment]
Ok, it is the same issue already fixed in Lomse. The fix is not yet propagated to LenMus. I will do it ASP.

**Comment by cecilios** [comment]
PR #56 should have fixed this issue. Please confirm. Thank you.

**Comment by ycollet** [comment]
Not yet. I still have the issue:

[  3%] Building CXX object CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp: Dans la fonction membre ‘void lenmus::CommandEventHandler::process_command_event(lomse::SpEventCommand)’:
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:401:77: erreur : no matching function for call to ‘static_pointer_cast(lomse::SpEventCommand&)’
                     boost::static_pointer_cast<EventControlPointMoved>(event) );
                                                                             ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_ldp_elements.h:40,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_ldp_factory.h:38,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_injectors.h:33,
                 from /home/collette/repositories/lenmus/lomse/trunk/include/lomse_interactor.h:34,
                 from /home/collette/repositories/lenmus/include/lenmus_tool_group.h:25,
                 from /home/collette/repositories/lenmus/include/lenmus_tool_box.h:26,
                 from /home/collette/repositories/lenmus/include/lenmus_command_event_handler.h:26,
                 from /home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:22:
/usr/include/boost/smart_ptr/shared_ptr.hpp:828:42: note : candidate: template<class T, class U> boost::shared_ptr<X> boost::static_pointer_cast(const boost::shared_ptr<U>&)
 template<class T, class U> shared_ptr<T> static_pointer_cast( shared_ptr<U> const & r ) BOOST_NOEXCEPT
                                          ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/smart_ptr/shared_ptr.hpp:828:42: note :   template argument deduction/substitution failed:
/home/collette/repositories/lenmus/src/app/lenmus_command_event_handler.cpp:401:77: note :   ‘lomse::SpEventCommand {aka std::shared_ptr<lomse::EventCommand>}’ is not derived from ‘const boost::shared_ptr<U>’
                     boost::static_pointer_cast<EventControlPointMoved>(event) );
                                                                             ^
CMakeFiles/lenmus.dir/build.make:182 : la recette pour la cible « CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o » a échouée
make[2]: *** [CMakeFiles/lenmus.dir/src/app/lenmus_command_event_handler.cpp.o] Erreur 1

**Comment by cecilios** [comment]
Sorry! I forgot to fix lenMus files. PR #58 should have fixed now all this, I hope ;-)

**Comment by ycollet** [comment]
Works fine now. Thanks.
Yann
